# Generated by Django 3.1.1 on 2021-06-28 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calories', '0002_auto_20200926_1854'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='person_of',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='person_of',
            new_name='user',
        ),
    ]
